### PR TITLE
Fix bug in Ska.arc5gl __init__

### PR DESCRIPTION
**Pull request by javierggt**
## Description

This seems like an obvious bug that was introduced in #14 when editing the docstring. A variable `args` is defined at a class scope, and then it is used inside a member function without qualification.

The following causes an error:
```python
import Ska.arc5gl
arc5 = Ska.arc5gl.Arc5gl(echo=True)
```

Tracking this error was not obvious, because for some reason the `__del__` method was called and it raised an exception 
```
AttributeError: 'Arc5gl' object has no attribute 'arc5gl'
```
that made me miss the real exception at first:
```
File /export/jgonzale/github-workflows/miniconda3/envs/ska3-masters-prime/lib/python3.10/site-packages/Ska/arc5gl/arc5gl.py:42, in Arc5gl.__init__(self, echo, timeout)
     40 self.prompt = 'ARC5GL> '
     41 spawn = pexpect.spawn if six.PY2 else pexpect.spawnu
---> 42 self.arc5gl = spawn('arc5gl', args=args, timeout=timeout)
     43 self.arc5gl.expect(self.prompt)
     44 self.echo = echo

UnboundLocalError: local variable 'args' referenced before assignment
```

## Interface impacts
None

### Unit tests

- [x] No unit tests

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests
This is all the testing I have done:
```python
import Ska.arc5gl
arc5 = Ska.arc5gl.Arc5gl(echo=True)
```

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]
Looks fine. Sorry for the original mistake.
